name: kube-tagger
description: Helm Chart to inject TAGS to EBS
version: 3.2.2
apiVersion: v1
kubeVersion: ">= 1.19.0"
tillerVersion: ">=2.11.1"
keywords:
- kube-tagger
engine: gotpl
appVersion: 0.1.3
home: https://github.com/sergiorua/kube-tagger
deprecated: false
maintainers:
- email: sandeep.lamba@grandparade.co.uk
  name: slamba
- email: sergio@rua.me.uk
  name: srua
sources:
- https://github.com/sergiorua/kube-tagger
